services:
  back:
    build:
      context: ./back
    container_name: campus-back
    env_file:
      - ./back/.env
    environment:
      PORT: 5000
      RUSTFS_ENDPOINT: http://rustfs:9000
    ports:
      - "5000:5000"
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped

  front:
    build:
      context: ./front
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3000/api
        API_PROXY_TARGET: http://back:5000
    container_name: campus-front
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - back
    restart: unless-stopped

  rustfs:
    image: rustfs/rustfs:latest
    container_name: rustfs-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      RUSTFS_ACCESS_KEY: admin
      RUSTFS_SECRET_KEY: motdepasse123
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
      RUSTFS_CONSOLE_ENABLE: "true"
      RUSTFS_OBS_LOGGER_LEVEL: error
    volumes:
      - rustfs_data:/data
    restart: unless-stopped

volumes:
  uploads:
  rustfs_data: